### ISSUE TITLE
add alias String for Tag

### ISSUE THREAD

**Issue by kechuan** [MartenM/flutter_bbcode#15]
some forums's bbcode doesn't always align.

example like:
- `spoiler` -> `mask`
- `s` -> `del`
...

it is not very convenient to customAgain just replace these text.
is it possible to add alias in the tag prop?

by the way the package it's very useful for me.

**Comment by MartenM** [comment]
I don't think aliases would be a good solution to solve the problem. Rather I think making the stylesheet tags able to take a non-default parameter that can be changed. That way you can just add your own tags with the existing functionality.
