### ISSUE TITLE
System font size

### ISSUE THREAD

**Issue by UlanNurmatov** [MartenM/flutter_bbcode#7]
The BBCodeText always remains the same size regardless of the system font size. For example it doesn't get bigger when font size is set to big.  
Is it how it should be?

**Comment by MartenM** [comment]
The default font size is set in the stylesheet [here](https://github.com/MartenM/flutter_bbcode/blob/839d48ef3fc975cee26388d157f66f7a9551bb2f/lib/src/style/stylesheet.dart#L24).

This is intentional, but I agree it should follow the system font size. I will check if this is possible to improve accessibility.

**Comment by MartenM** [comment]
The project has been updated [`1.4.1`] to support different font sizes through the accessibility menu. This should hopefully resolve the issues you were having. If not feel free to re-open the issue.

Leaving stars on GitHub and likes on pub.dev is also highly appreciated :)

**Comment by UlanNurmatov** [comment]
Thanks. It seems to resolve the issue. 
One more question. When switching to dark mode, bbcode text remains dark. What should I add to ThemeData to make it white? This is my code: 
```
darkTheme: ThemeData(
              appBarTheme: AppBarTheme(
                  color: mainColor,
                  foregroundColor: Colors.white,
                  iconTheme: IconThemeData(color: Colors.white)),
              colorScheme: ColorScheme.fromSwatch().copyWith(
                  primary: mainColor,
                  secondary: Colors.white,
                  brightness: Brightness.dark))
```

**Comment by MartenM** [comment]
Currently, the theme data is not being used by the BBCode widget. 
I should probably look into that as well.

**Edit:** You can change the default style of the BBCode widget by passing in a style sheet. If you query your theme and supply it that it should also work properly I think. I opened a issue #9 for theme ThemeData though.
